### PR TITLE
LIT-528106 Allow handling of duplicated ids

### PR DESCRIPTION
**Pull request by mbartenev-atypon**

### CODE REVIEW

**Review by hhusban — APPROVED** [review]
Looks good

**Comment by mnatsheh** [comment]
@mbartenev-atypon is this the only PR related to the duplicate IDs problem?

**Comment by mbartenev-atypon** [comment]
> @mbartenev-atypon is this the only PR related to the duplicate IDs problem?

Here is the other one
https://github.com/Atypon-OpenSource/manuscripts-article-editor/pull/239/files

**Comment by mbartenev-atypon** [comment]
@mnatsheh looks like we don't need that PR anymore. Closing.

**Comment by mnatsheh** [comment]
@mbartenev-atypon was the fix included somewhere else? did we handle the issue in some other way?

**Comment by mbartenev-atypon** [comment]
hm, I was under impression that it was used on some other branch for the purposes of testing zax and was merged then. But now I'm checking the code and I see that's not on master so it was never merged, although the ticket is closed. Let me know if we need to merged it.

**Comment by mnatsheh** [comment]
I can still see tickets being filed with the "duplicate ids in model map" error (e.g. LEAN-3047).

**Pull request merged**
