### PR TITLE
LEAN-2402 -- Remove bundled data

### PR DESCRIPTION
**Pull request by hhusban**

### CODE REVIEW

**Review by asouqi — CHANGES_REQUESTED** [review]
can we remove: `loadBundledData` & [shared-data](https://github.com/Atypon-OpenSource/manuscripts-transform/blob/955b92026f2413b2720865da5213b2fc6ee3c11b/src/transformer/shared-data.ts)

**Comment by hhusban** [comment]
@asouqi I update the PR and removed both loadBundledData & shared-data, plus any lingering functions left

**Review by asouqi — APPROVED** [review]

**Review by mnatsheh — APPROVED** [review]

**Comment by mnatsheh** [comment]
Do we still need the manuscripts/data dependency?

**Comment by hhusban** [comment]
@mnatsheh  there is still a couple of references under, which are used for in the front-parser. 
src/transformer/bundles-data.ts

**Pull request merged**
