### PR TITLE
LEAN-3168 Restoring not creating empty section implemented in LEAN-3069

### PR DESCRIPTION
**Pull request by mbartenev-atypon**

### CODE REVIEW

**Comment by mbartenev-atypon** [comment]
@mnatsheh should we go with a testing process on this ticket or is it fine to merge straight away?

**Review by mnatsheh — APPROVED** [review]
As long as you tried it locally, it should be fine to merge. 

I'm assuming the problem is not actually related to your fix in LEAN-3168.

**Comment by mbartenev-atypon** [comment]
> As long as you tried it locally, it should be fine to merge.
> 
> I'm assuming the problem is not actually related to your fix in LEAN-3168.

Yes, it's not related.

**Comment by mbartenev-atypon** [comment]
I've added that testing to demonstrate that this fix prevents empty section created and so we can monitor that in future.

**Pull request merged**
