### PR TITLE
LEAN-2403: Remove bundle detection from JATS import

### PR DESCRIPTION
**Pull request by mbetamony**

### CODE REVIEW

**Comment by mnatsheh** [comment]
@mbetamony did you try to import a package and check if it goes through?

**Comment by mnatsheh** [comment]
Also, please fix the failing test.

**Comment by mbetamony** [comment]
> @mbetamony did you try to import a package and check if it goes through?

Yes, I did via pressroom and everything works fine

> Also, please fix the failing test.

Fixed, the snapshot had information about MPBundle

**Comment by mbetamony** [comment]
Fixed the manuscripts-data to use the new number found in this [PR](https://github.com/Atypon-OpenSource/manuscripts-data/pull/4)
Fixed version number

**Comment by mnatsheh** [comment]
rerun

**Comment by mnatsheh** [comment]
@mbetamony you need to run `yarn install` locally and push the updated `yarn.lock` file.

**Comment by mbetamony** [comment]
> @mbetamony you need to run `yarn install` locally and push the updated `yarn.lock` file.
Done, also removed ticket number from version number since no QA testing is required for this

**Comment by mbetamony** [comment]
> @mbetamony there is still a failing test.

test are failing in `manuscript-dependencies.test.ts`, which is testing `manuscript-dependencies.ts`
The failing test is a result of this [PR](https://github.com/Atypon-OpenSource/manuscripts-data/pull/2), It's failing to fetch the data from some of these files.(since manuscripts-data version  is now updated)
I don't see a need or a usage for `manuscript-dependencies.ts`, should I proceed with removing it along with the test file?

**Review by mnatsheh — APPROVED** [review]
I'm guessing the master rebase picked up https://github.com/Atypon-OpenSource/manuscripts-transform/pull/15 and fixed the issue.

**Pull request merged**
